[[Quiver]]
arch = "aarch64"
git-tree-sha1 = "02f494de763ea2b8013aaf735d316717d12e8db4"
os = "macos"

    [[Quiver.download]]
    sha256 = "acb29faa2a0d67772f2b0676e03e5ee6e548a815244663726a7e8e410f8bb8ff"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.6.0+0/Quiver.v0.6.0.aarch64-apple-darwin.tar.gz"
[[Quiver]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a8ea3beb58bd4a401d4d24b94da3295ab7aa984"
libc = "glibc"
os = "linux"

    [[Quiver.download]]
    sha256 = "bf9f41155bfd8ab15e774945edfd3eae5827416ebb6cc44dabc3130771ebff12"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.6.0+0/Quiver.v0.6.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Quiver]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e064cd3ff47fb2e8e6633cc2a3677e77f9478acf"
libc = "musl"
os = "linux"

    [[Quiver.download]]
    sha256 = "110f66ccb1dab6502bc3458a0da143099507f60459eae486b3b477208ff985af"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.6.0+0/Quiver.v0.6.0.aarch64-linux-musl-cxx11.tar.gz"
[[Quiver]]
arch = "aarch64"
git-tree-sha1 = "01e1fa69bf078f2b8086b90bb24e57d236dd0fee"
os = "freebsd"

    [[Quiver.download]]
    sha256 = "4bdeac9e4c7e888d881f02b2becce355366a95c07f575c585448203fc1de2397"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.6.0+0/Quiver.v0.6.0.aarch64-unknown-freebsd.tar.gz"
[[Quiver]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a969ff278a6b595763f0d509ab97e44775621e3"
libc = "glibc"
os = "linux"

    [[Quiver.download]]
    sha256 = "e95630f1270bc86f2587d974db7450b160910afc62fa3a1e2fe56d3d09ef898a"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.6.0+0/Quiver.v0.6.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Quiver]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5874e8e0548d9c9fe4348c7aaad02cecb080e0e1"
libc = "musl"
os = "linux"

    [[Quiver.download]]
    sha256 = "2f58ba09db3c10b7f81f7f55e808556ee6de9d230df44683565ca76a66d2c132"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.6.0+0/Quiver.v0.6.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Quiver]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb8cc44acb46435d74d25ba730c49032873596d6"
libc = "glibc"
os = "linux"

    [[Quiver.download]]
    sha256 = "4818ceaea3d153a62de44506a9fb9a447e84eb61790d2bc7cd60ea7644c29b30"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.6.0+0/Quiver.v0.6.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Quiver]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08d4d6d64d06564f89110b0a091f93d149c9ad7a"
libc = "musl"
os = "linux"

    [[Quiver.download]]
    sha256 = "49a664e4b4f6bf22284f6f2631ecfd92423fb47336f1ef896cdacb85d8f89d5c"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.6.0+0/Quiver.v0.6.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Quiver]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "76270055734000a8ef1a69d14c55b8586dbc7ff6"
libc = "glibc"
os = "linux"

    [[Quiver.download]]
    sha256 = "614703ebba1ba46ae41871981946e71a125b2185dc3cf00eed346df0cc6dd8b8"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.6.0+0/Quiver.v0.6.0.i686-linux-gnu-cxx11.tar.gz"
[[Quiver]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7378ef2e7ca4baef2dbf903f7c373a890964be2"
libc = "musl"
os = "linux"

    [[Quiver.download]]
    sha256 = "088109207921cf29703f2ef6c0127578ba8c096a466cea20a12f2bac4e88c910"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.6.0+0/Quiver.v0.6.0.i686-linux-musl-cxx11.tar.gz"
[[Quiver]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "96aaceef126d10a72b22ea1f53daf57be2f1915c"
os = "windows"

    [[Quiver.download]]
    sha256 = "25cee41d33eaae8ec76f959eba2655a61c427854b19a32ceaafb5ccf1a3418a2"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.6.0+0/Quiver.v0.6.0.i686-w64-mingw32-cxx11.tar.gz"
[[Quiver]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "572de10f789c8e36936301c2b6e03fb0aff12a82"
libc = "glibc"
os = "linux"

    [[Quiver.download]]
    sha256 = "15bfd608bfffc949995bc7fd69bbe077f476440b4477ea6820884010d158bdca"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.6.0+0/Quiver.v0.6.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Quiver]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "62a6365022c271ec29f27da1cdd87ff68c67e701"
libc = "glibc"
os = "linux"

    [[Quiver.download]]
    sha256 = "662bf75f923c63680977e6511de8cafe207a42de3d24a7c114ae00362c2c760f"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.6.0+0/Quiver.v0.6.0.riscv64-linux-gnu-cxx11.tar.gz"
[[Quiver]]
arch = "x86_64"
git-tree-sha1 = "f325e4b5871ee4257b2441043dd5c4b0a600f3fb"
os = "macos"

    [[Quiver.download]]
    sha256 = "601ec98ad36db1bc2fbbc319f4a96a3f2277b3d5f92b410420e93de6f86fcb23"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.6.0+0/Quiver.v0.6.0.x86_64-apple-darwin.tar.gz"
[[Quiver]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd8011f884587087093f78391238436ee3c340b0"
libc = "glibc"
os = "linux"

    [[Quiver.download]]
    sha256 = "92a08c6879a5e6fec4f1c45dea512cbcd06cf9659c2569535d2a1aa6367bbceb"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.6.0+0/Quiver.v0.6.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Quiver]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a24202857857948feb1ce47dcf3703350e1e74d"
libc = "musl"
os = "linux"

    [[Quiver.download]]
    sha256 = "d6664c92b67ae52712ed97eb0ddf2df4cc5eb542fa430c4319d1243ea7ed13e6"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.6.0+0/Quiver.v0.6.0.x86_64-linux-musl-cxx11.tar.gz"
[[Quiver]]
arch = "x86_64"
git-tree-sha1 = "835854534152fc4bbcca1e2f666148fa02da1162"
os = "freebsd"

    [[Quiver.download]]
    sha256 = "7bf1086b8b56c5af17cf9721d3972699a0e50debc2c240f9ffbc35d52d589a1e"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.6.0+0/Quiver.v0.6.0.x86_64-unknown-freebsd.tar.gz"
[[Quiver]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf2685fb0d87789ebdf89a56b16899640ee45273"
os = "windows"

    [[Quiver.download]]
    sha256 = "7c95f88a22fa7a42c8decc40c917bc5a3417519575d079009ee7c4850b0f5788"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.6.0+0/Quiver.v0.6.0.x86_64-w64-mingw32-cxx11.tar.gz"
