[[Quiver]]
arch = "aarch64"
git-tree-sha1 = "11f38c68427e2290c30bd8e668db0577399c0b78"
os = "macos"

    [[Quiver.download]]
    sha256 = "251f04ef58abdd85a9c0b9adeb5a74e11577eb9a8a67e8ba136e88d134b3d2b7"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.7.9+0/Quiver.v0.7.9.aarch64-apple-darwin.tar.gz"
[[Quiver]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "230b309bbf57a68a1e3f41367431422c1458b349"
libc = "glibc"
os = "linux"

    [[Quiver.download]]
    sha256 = "58f0551fbb9d93f8a72b0c23995d45bd50a168158f5ba8a29b367d8a56f5fb92"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.7.9+0/Quiver.v0.7.9.aarch64-linux-gnu-cxx11.tar.gz"
[[Quiver]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b8fb26325ebf9be4571498ea2834db682357508"
libc = "musl"
os = "linux"

    [[Quiver.download]]
    sha256 = "3b80d4da530183e7cf81994cccda2a43d91cd2614a5d1924c80d6f4d6976e70c"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.7.9+0/Quiver.v0.7.9.aarch64-linux-musl-cxx11.tar.gz"
[[Quiver]]
arch = "aarch64"
git-tree-sha1 = "95a765f033d1000edd2534f7032dc90f954ba95f"
os = "freebsd"

    [[Quiver.download]]
    sha256 = "2a1fc720f58a6d7fad2b1ad50e05cce6898c156157323afcbe36e32d36b6a437"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.7.9+0/Quiver.v0.7.9.aarch64-unknown-freebsd.tar.gz"
[[Quiver]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cefd1bfe53809440a2b859ee4f359cd56a6425ea"
libc = "glibc"
os = "linux"

    [[Quiver.download]]
    sha256 = "c652a71fa4f89ad16b21d458e66350e517091b5bbd52645a567a5c1399041b7f"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.7.9+0/Quiver.v0.7.9.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Quiver]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac4609c71aead7d93cdef5ceb9d6cb9fc3f721e0"
libc = "musl"
os = "linux"

    [[Quiver.download]]
    sha256 = "58eb9ca7ed91dd877ee6cef52bf9dbe73662470c8a47428bbf18c08d0906e49e"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.7.9+0/Quiver.v0.7.9.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Quiver]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b3dfe2d5f239e64488ee0e22301ef73261d8b6f8"
libc = "glibc"
os = "linux"

    [[Quiver.download]]
    sha256 = "5c6c415f67e3f48a5996e73ec23e69b107e57bdc6ecc1aa3ce546024d132d1ab"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.7.9+0/Quiver.v0.7.9.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Quiver]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e64cd1c00c701542c1cbed0a27a72374b27dceb"
libc = "musl"
os = "linux"

    [[Quiver.download]]
    sha256 = "a8b6523dfdaf008d4790685f2172fe7ad9996cdcb7fb20b19edf9bdbbc8c165c"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.7.9+0/Quiver.v0.7.9.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Quiver]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3825bb1b0ee9f681865f3737f3017eba169af86"
libc = "glibc"
os = "linux"

    [[Quiver.download]]
    sha256 = "75459d96f6787e6b546e6be6da5b27b51b4e47d72bdde6cfef67e0c2ffe712c3"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.7.9+0/Quiver.v0.7.9.i686-linux-gnu-cxx11.tar.gz"
[[Quiver]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "02a4b3241bee2066eca24a0cbcd38ae88e48f733"
libc = "musl"
os = "linux"

    [[Quiver.download]]
    sha256 = "8e2f79da7618b53c903e36fd14fed53c01e2b78dbd188e15c842c058594669ba"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.7.9+0/Quiver.v0.7.9.i686-linux-musl-cxx11.tar.gz"
[[Quiver]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1b8c2fd50c069935fb56ab522b5ff7ef43c97f35"
os = "windows"

    [[Quiver.download]]
    sha256 = "103f3afa4b10f991ac6f1ac00827a0e11a95c71ef4c2347b52dd8e3eeece0198"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.7.9+0/Quiver.v0.7.9.i686-w64-mingw32-cxx11.tar.gz"
[[Quiver]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "99284277302a5526c048c2d50f351d555e261458"
libc = "glibc"
os = "linux"

    [[Quiver.download]]
    sha256 = "09d02ab9fa03533df9ff7a5d949ed16b60104640f5584c6bbee68889eb905773"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.7.9+0/Quiver.v0.7.9.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Quiver]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13b5c002396e54325df2d100ff6c2308c66ccd97"
libc = "glibc"
os = "linux"

    [[Quiver.download]]
    sha256 = "348882c48e9a2890303c2358df96e9be3ff1b4932171d68d97564b7b1e2f2065"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.7.9+0/Quiver.v0.7.9.riscv64-linux-gnu-cxx11.tar.gz"
[[Quiver]]
arch = "x86_64"
git-tree-sha1 = "802212a0098817963b36d1ceb890ec7fd57b54a7"
os = "macos"

    [[Quiver.download]]
    sha256 = "9a3e756682a1f456ee8f9c8a3a3d6da539eb9e9bc656e3fd0e82be284699c8f1"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.7.9+0/Quiver.v0.7.9.x86_64-apple-darwin.tar.gz"
[[Quiver]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9837d99ec182f65fd6166fd85c2bb6a406919ee0"
libc = "glibc"
os = "linux"

    [[Quiver.download]]
    sha256 = "d131f269af760062f6ae9ca6ab29c52313b2b68b2fa823c479cfebb45d4f5f1f"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.7.9+0/Quiver.v0.7.9.x86_64-linux-gnu-cxx11.tar.gz"
[[Quiver]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d4f9642d10067b83ae53deb201f6f81e6e0ac9d"
libc = "musl"
os = "linux"

    [[Quiver.download]]
    sha256 = "68b1302adcfa2ac5d08a600361d6f46ff586b2034fff5423d79f3bfac1925cec"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.7.9+0/Quiver.v0.7.9.x86_64-linux-musl-cxx11.tar.gz"
[[Quiver]]
arch = "x86_64"
git-tree-sha1 = "bae27e60a7c126c733a4781651e9f0e4f14c0196"
os = "freebsd"

    [[Quiver.download]]
    sha256 = "b69f23cde2e30bd45e496b7a90ce4a80e4bf74af267bb1842123a243cdb38b50"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.7.9+0/Quiver.v0.7.9.x86_64-unknown-freebsd.tar.gz"
[[Quiver]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f32a806bf860b1403eedb40ac1048eebd2a0374b"
os = "windows"

    [[Quiver.download]]
    sha256 = "5234392ea589a3659f3bad9780ceee7d2dc5cf8788b630ccf0afa4b2a115c5fd"
    url = "https://github.com/JuliaBinaryWrappers/Quiver_jll.jl/releases/download/Quiver-v0.7.9+0/Quiver.v0.7.9.x86_64-w64-mingw32-cxx11.tar.gz"
