# Autogenerated wrapper script for Quiver_jll for aarch64-apple-darwin
export libquiver, libquiver_c

JLLWrappers.@generate_wrapper_header("Quiver")
JLLWrappers.@declare_library_product(libquiver, "@rpath/libquiver.0.dylib")
JLLWrappers.@declare_library_product(libquiver_c, "@rpath/libquiver_c.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libquiver,
        "lib/libquiver.0.6.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libquiver_c,
        "lib/libquiver_c.0.6.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
