# Autogenerated wrapper script for Quiver_jll for armv6l-linux-gnueabihf-cxx11
export libquiver, libquiver_c

JLLWrappers.@generate_wrapper_header("Quiver")
JLLWrappers.@declare_library_product(libquiver, "libquiver.so.0")
JLLWrappers.@declare_library_product(libquiver_c, "libquiver_c.so.0")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libquiver,
        "lib/libquiver.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libquiver_c,
        "lib/libquiver_c.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
