# Autogenerated wrapper script for Quiver_jll for x86_64-w64-mingw32-cxx11
export libquiver, libquiver_c

JLLWrappers.@generate_wrapper_header("Quiver")
JLLWrappers.@declare_library_product(libquiver, "libquiver.dll")
JLLWrappers.@declare_library_product(libquiver_c, "libquiver_c.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libquiver,
        "bin\\libquiver.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libquiver_c,
        "bin\\libquiver_c.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
